# From Python lists

In [1]:
import pandas as pd

data = [['alice', 54], ['alpha', 74], ['ando', 34]]

df = pd.DataFrame(data, columns=["name","age"])
df

    name  age
0  alice   54
1  alpha   74
2   ando   34

# from dictionary of lists

In [4]:
import pandas as pd

data = {
    "Name" : ["slice" , "karan" , "komal"],
    "age" : ["23", "25", "24"]
}

df = pd.DataFrame(data)
df

    Name age
0  slice  23
1  karan  25
2  komal  24

# From numpy Arrays

In [7]:
import numpy as ka

arr = ka.array([[1,2],[4,5]])
df = pd.DataFrame(arr, columns = ["A", "B"])
df

   A  B
0  1  2
1  4  5

In [9]:
import pandas as pd
df = pd.read_excel("data.xlsx")

In [10]:
 df

     name school  marks
0   karan    dsd     43
1   kunal    ads     23
2    bana    aew     86
3  monika    gfh     45
4   kirti    seq     78
5   komal    yhu     87
6   sheru    twq     98
7   mouse    ywq     67

In [13]:
import pandas as pd
df = pd.read_json("data.json")

In [14]:
df

    Name    lang
0  Karan  python
1  narak       c

In [15]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

In [16]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [18]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [19]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [21]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [23]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [24]:
df.shape

(244, 7)