In [1]:
import pandas as pd
df = pd.read_excel("data3.xlsx")

In [2]:
df

      Name   Age         City Gender              Email  Join Date
0    Alice  25.0     New York      F  alice@example.com 2021-05-01
1  Charlie   NaN        Delhi      M    charlie@example 2021-07-20
2      Bob  30.0  Los Angeles      M    bob@example.com 2020-06-15
3  Charlie   NaN        Delhi      M    charlie@example 2021-07-20
4    David  22.0       Mumbai      M  david@example.com 2019-11-12
5      NaN  28.0        Delhi      F     eve@domain.com        NaT
6    Alice  25.0     New York      F  alice@example.com 2021-05-01
7    Alice  25.0     New York      F  alice@example.com 2021-05-01
8  Charlie   NaN        Delhi      M    charlie@example 2021-07-20

In [3]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [4]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [5]:
df.dropna()

    Name   Age         City Gender              Email  Join Date
0  Alice  25.0     New York      F  alice@example.com 2021-05-01
2    Bob  30.0  Los Angeles      M    bob@example.com 2020-06-15
4  David  22.0       Mumbai      M  david@example.com 2019-11-12
6  Alice  25.0     New York      F  alice@example.com 2021-05-01
7  Alice  25.0     New York      F  alice@example.com 2021-05-01

In [6]:
df.dropna(axis=1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [7]:
df.fillna(0)

      Name   Age         City Gender              Email            Join Date
0    Alice  25.0     New York      F  alice@example.com  2021-05-01 00:00:00
1  Charlie   0.0        Delhi      M    charlie@example  2021-07-20 00:00:00
2      Bob  30.0  Los Angeles      M    bob@example.com  2020-06-15 00:00:00
3  Charlie   0.0        Delhi      M    charlie@example  2021-07-20 00:00:00
4    David  22.0       Mumbai      M  david@example.com  2019-11-12 00:00:00
5        0  28.0        Delhi      F     eve@domain.com                    0
6    Alice  25.0     New York      F  alice@example.com  2021-05-01 00:00:00
7    Alice  25.0     New York      F  alice@example.com  2021-05-01 00:00:00
8  Charlie   0.0        Delhi      M    charlie@example  2021-07-20 00:00:00

In [8]:
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [9]:
df.ffill()

      Name   Age         City Gender              Email  Join Date
0    Alice  25.0     New York      F  alice@example.com 2021-05-01
1  Charlie  25.0        Delhi      M    charlie@example 2021-07-20
2      Bob  30.0  Los Angeles      M    bob@example.com 2020-06-15
3  Charlie  30.0        Delhi      M    charlie@example 2021-07-20
4    David  22.0       Mumbai      M  david@example.com 2019-11-12
5    David  28.0        Delhi      F     eve@domain.com 2019-11-12
6    Alice  25.0     New York      F  alice@example.com 2021-05-01
7    Alice  25.0     New York      F  alice@example.com 2021-05-01
8  Charlie  25.0        Delhi      M    charlie@example 2021-07-20

In [10]:
df.bfill()

      Name   Age         City Gender              Email  Join Date
0    Alice  25.0     New York      F  alice@example.com 2021-05-01
1  Charlie  30.0        Delhi      M    charlie@example 2021-07-20
2      Bob  30.0  Los Angeles      M    bob@example.com 2020-06-15
3  Charlie  22.0        Delhi      M    charlie@example 2021-07-20
4    David  22.0       Mumbai      M  david@example.com 2019-11-12
5    Alice  28.0        Delhi      F     eve@domain.com 2021-05-01
6    Alice  25.0     New York      F  alice@example.com 2021-05-01
7    Alice  25.0     New York      F  alice@example.com 2021-05-01
8  Charlie   NaN        Delhi      M    charlie@example 2021-07-20

In [11]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [13]:
df.drop_duplicates()

      Name   Age         City Gender              Email  Join Date
0    Alice  25.0     New York      F  alice@example.com 2021-05-01
1  Charlie   NaN        Delhi      M    charlie@example 2021-07-20
2      Bob  30.0  Los Angeles      M    bob@example.com 2020-06-15
4    David  22.0       Mumbai      M  david@example.com 2019-11-12
5      NaN  28.0        Delhi      F     eve@domain.com        NaT

In [14]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [15]:
df["City"].str.contains("delhi", case=False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [16]:
df2 = df.dropna().copy()

In [17]:
df2["Age"] = df2["Age"].astype(int)

In [18]:
df2

    Name  Age         City Gender              Email  Join Date
0  Alice   25     New York      F  alice@example.com 2021-05-01
2    Bob   30  Los Angeles      M    bob@example.com 2020-06-15
4  David   22       Mumbai      M  david@example.com 2019-11-12
6  Alice   25     New York      F  alice@example.com 2021-05-01
7  Alice   25     New York      F  alice@example.com 2021-05-01

In [20]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      int64
 2   City       5 non-null      object
 3   Gender     5 non-null      object
 4   Email      5 non-null      object
 5   Join Date  5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 280.0+ bytes

In [21]:
df2

    Name  Age         City Gender              Email  Join Date
0  Alice   25     New York      F  alice@example.com 2021-05-01
2    Bob   30  Los Angeles      M    bob@example.com 2020-06-15
4  David   22       Mumbai      M  david@example.com 2019-11-12
6  Alice   25     New York      F  alice@example.com 2021-05-01
7  Alice   25     New York      F  alice@example.com 2021-05-01

In [24]:
df2["Age Group"] = df2["Age"].apply(lambda x: "Adult" if x>=26 else "Minor")

In [25]:
df2

    Name  Age         City Gender              Email  Join Date Age Group
0  Alice   25     New York      F  alice@example.com 2021-05-01     Minor
2    Bob   30  Los Angeles      M    bob@example.com 2020-06-15     Adult
4  David   22       Mumbai      M  david@example.com 2019-11-12     Minor
6  Alice   25     New York      F  alice@example.com 2021-05-01     Minor
7  Alice   25     New York      F  alice@example.com 2021-05-01     Minor

In [26]:
gender_map = {"M" : "Male", "F" : "Female"}
df2["Gender"] = df2["Gender"].map(gender_map)

In [27]:
df2

    Name  Age         City  Gender              Email  Join Date Age Group
0  Alice   25     New York  Female  alice@example.com 2021-05-01     Minor
2    Bob   30  Los Angeles    Male    bob@example.com 2020-06-15     Adult
4  David   22       Mumbai    Male  david@example.com 2019-11-12     Minor
6  Alice   25     New York  Female  alice@example.com 2021-05-01     Minor
7  Alice   25     New York  Female  alice@example.com 2021-05-01     Minor

In [28]:
df["City"].replace({"Del": "Delhi", "Mum" : "Mumbai"})

0       New York
1          Delhi
2    Los Angeles
3          Delhi
4         Mumbai
5          Delhi
6       New York
7       New York
8          Delhi
Name: City, dtype: object